[package]
name = "ltools"
version = "1.0.0"
edition = "2021"
description = "Núcleo nativo y seguro para LTools"
license = "MIT"

[workspace]
members = ["crates/native-argv"]
resolver = "2"

[features]
default = []
cli = []

[dependencies]
base64 = "0.23"
ed25519-dalek = { version = "2.2", features = ["pem"] }
libc = "0.2"
ltools-argv = { path = "crates/native-argv" }
sha2 = "0.11"
serde_json = "1.0.151"
semver = "1.0"
ureq = { version = "3.4.0", default-features = false, features = ["rustls"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_LibraryLoader",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_UI_Controls",
    "Win32_Graphics_Gdi",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }

[profile.release]
strip = true
lto = true
codegen-units = 1
